namespace CAS
{
    public enum AdNetwork
    {
        GoogleAds,
        Vungle,
        Kidoz,
        Chartboost,
        UnityAds,
        AppLovin,
        SuperAwesome,
        StartApp,
        AdColony,
        FacebookAN,
        InMobi,
        MobFox,
        MyTarget,
        CrossPromotion,
        IronSource,
        YandexAds,
        OwnVAST,
        MAX,
        Smaato,
        MoPub,
        Tapjoy,
        Fyber,
        FairBid,
        Mintegral,
        Pangle,
        Admost,
        Verizon,
        AmazonAds,
        HyperMX
    }
}